source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!

xcodeproj 'PRRadialMenuPopover'
use_frameworks!

target 'PRRadialMenuPopover_Example' do
  pod "PRRadialMenuPopover", :path => "../"

  target 'PRRadialMenuPopover_Tests' do
    pod "PRRadialMenuPopover", :path => "../"
    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
